config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :athletes

  resources :competitions do
    resources :bibs, only: [:index, :create]
    resources :rounds, only: [:new, :create]
  end

  resources :bibs, only: [:edit, :update, :destroy]

  resources :rounds, only: [:show, :edit, :update, :destroy] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, only: [:show, :edit, :update, :destroy] do
    resources :attempts, only: [:new, :create, :index]
  end

  resources :attempts, only: [:edit, :update, :destroy]
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :user
  has_many :bibs
  has_many :athletes, through: :bibs
  has_many :rounds
  has_many :routes, through: :rounds
  has_many :attempts, through: :routes

  validates :name, presence: true
  validates :user, presence: true
  validates :start_date, presence: true

  def leaderboard
    final_round.leaderboard
  end

  def final_round
    rounds.order(:number).last
  end

  STATES = ['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
            'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
            'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
            'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
            'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_user!, only:
    [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_owner!, only: [:edit, :update, :destroy]

  def index
    @competitions = Competition.order(start_date: :desc)
  end

  def show
    @competition = Competition.includes(
      :rounds, :routes, :attempts).find(params[:id])
  end

  def new
    @competition = Competition.new
    @states = Competition::STATES
  end

  def create
    @competition = current_user.competitions.new(competition_params)
    @states = Competition::STATES

    if @competition.save
      flash[:notice] = 'New competition created'
      redirect_to competition_path(@competition)
    else
      flash[:alert] = @competition.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @competition = Competition.find(params[:id])
    @states = Competition::STATES
  end

  def update
    @competition = Competition.find(params[:id])
    @states = Competition::STATES

    if @competition.update(competition_params)
      flash[:notice] = 'Competition updated'
      redirect_to competition_path(@competition)
    else
      flash[:alert] = @competition.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @competition = Competition.find(params[:id])

    if @competition.destroy
      flash[:alert] = "Competition deleted"
      redirect_to competitions_path
    else
      flash[:alert] = @competition.errors.full_messages.join(". ")
      render :show
    end
  end

  protected

  def owner
    Competition.find(params[:id]).user
  end

  def competition_params
    params.require(:competition).permit(
      :name, :gender, :division, :start_date, :end_date, :gym, :city, :state)
  end
end

app/views/competitions/edit.html.erb
<h2><%= @competition.name %><h2>
<h3><%= @competition.division %>&nbsp;<%= @competition.gender %></h3>

<%= form_for @competition do |f| %>
  <%= f.label :name, 'Name*'%>
  <%= f.text_field :name %>

  <%= f.label :start_date, 'Start Date*' %>
  <%= f.date_field :start_date %>

  <%= f.label :end_date, 'End Date' %>
  <%= f.date_field :end_date %>

  <%= f.label :gender %>
  <%= f.select :gender, ["Female", "Male", "Mixed"], include_blank: true %>

  <%= f.label :division %>
  <%= f.text_field :division %>

  <%= f.label :gym, 'Host Gym' %>
  <%= f.text_field :gym %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.select :state, @states, include_blank: true %>

  <p>* Only name and start date are required. </p>

  <%=
    f.submit (f.object.new_record? ? "Create Competition" :
    "Update Competition"), class: "button small"
  %>
  &nbsp;
  <%=
    link_to "Delete Competition", competition_path(@competition),
    method: :delete, class: "button small",
    data: { confirm: "This will delete competition permanently" }
  %>
<% end %>

app/views/competitions/index.html.erb
<h1>All Competitions</h1>

<%= link_to "Create New Competition", new_competition_path, class: "button small"  %>

<table class="center">
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Division</th>
      <th>Gym</th>
      <th>City</th>
      <th>State</th>
    </tr>
  </thead>
  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.start_date %></td>
        <td><%= link_to competition.name, competition_path(competition) %></td>
        <td><%= competition.gender %></td>
        <td><%= competition.division %></td>
        <td><%= competition.gym %></td>
        <td><%= competition.city %></td>
        <td><%= competition.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/competitions/new.html.erb
<h2>New Competition</h2>

<%= form_for @competition do |f| %>
  <%= f.label :name, 'Name*'%>
  <%= f.text_field :name %>

  <%= f.label :start_date, 'Start Date*' %>
  <%= f.date_field :start_date %>

  <%= f.label :end_date, 'End Date' %>
  <%= f.date_field :end_date %>

  <%= f.label :gender %>
  <%= f.select :gender, ["Female", "Male", "Mixed"], include_blank: true %>

  <%= f.label :division %>
  <%= f.text_field :division %>

  <%= f.label :gym, 'Host Gym' %>
  <%= f.text_field :gym %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.select :state, @states, include_blank: true %>

  <p>* Only name and start date are required. </p>

  <%= f.submit "Create Competition", class: "button small" %>
<% end %>

app/views/competitions/show.html.erb
<h2><%= @competition.name %></h2>

<h5>
  <%= @competition.gender %>&nbsp;
  <%= @competition.division %>
  <br>
  <%= @competition.gym %>&nbsp;
  <%= @competition.city %>&nbsp;
  <%= @competition.state %>
  <br>
  <%= @competition.start_date.strftime(format='%D') %>&nbsp;
  <% if @competition.end_date %>
    -&nbsp;<%= @competition.end_date.strftime(format='%D') %>
  <% end %>
</h5>

<% unless current_user == @competition.user %>
  <br>
  <%=
    link_to "Create your own competition to add rounds and record attempts",
    new_competition_path, class: "button small"
  %>
<% end %>

<div class="row">
  <div class="small-2 columns">
    <ul class=side-nav>
      <li>
        <h4><strong>Rounds</strong></h4>
      </li>
      <% @competition.rounds.each do |round| %>
        <li>
          <%= link_to round.name, round_path(round),
            class: "button small success" %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="small-10 columns">
    <% unless @competition.final_round.nil? %>
      <table class="center">
        <thead>
          <tr>
            <th>Standing</th>
            <th>Athlete</th>
            <th>Round Tops</th>
            <th>Round Points</th>
            <% @competition.final_round.routes.each do |route| %>
              <th><%= link_to route.name, route_path(route) %><br>Route</th>
            <% end %>

            <% @competition.rounds.each do |round| %>
              <% unless round == @competition.final_round %>
                <th><%= link_to round.name, round_path(round) %><br>Round</th>
              <% end %>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @competition.leaderboard.each_with_index do |r_score, i| %>
            <tr>
              <td><%= i + 1 %></td>
              <td><%=
                link_to r_score.athlete.name_last_first,
                athlete_path(r_score.athlete)
              %></td>
              <td><%= r_score.tops %></td>
              <td><%= r_score.score %></td>
              <% @competition.final_round.routes.each do |route| %>
                <td><%= route.athlete_rank(r_score.athlete) %></td>
              <% end %>

              <% @competition.rounds.reverse_each do |round| %>
                <% unless round == @competition.final_round %>
                  <td>
                    <%= round.round_tops(r_score.athlete) %>&nbsp;&nbsp;-&nbsp;
                    <%= round.round_score(r_score.athlete) %>
                  </td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <p>
        Ranking points are shown for routes in the current round
        <br>
        (T) indicates a "Top" (climber achieved maximum score)
        <br>
        Previous round scores displayed as "Tops - Round Points"
        <br>
      </p>
    <% else %>
      <h3>Start List</h3>

      <table class="center">
        <thead>
          <tr>
            <th>Name</th>
            <th>Birth Year</th>
            <th>Gender</th>
            <th>Team</th>
          </tr>
        </thead>
        <tbody>
          <% @competition.athletes.each do |athlete| %>
            <tr>
              <td><%= link_to athlete.name_last_first, athlete_path(athlete) %></td>
              <td><%= athlete.date_of_birth.year %></td>
              <td><%= athlete.gender %></td>
              <td><%= athlete.team %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <% if current_user == @competition.user %>
      <%=
        link_to "Register Athletes", competition_bibs_path(@competition),
        class: "button small"
      %>
      &nbsp;&nbsp;
      <%=
        link_to "Add Round", new_competition_round_path(@competition),
        class: "button small"
      %>
      &nbsp;&nbsp;
      <%=
        link_to "Edit Competition", edit_competition_path(@competition),
        class: "button small"
      %>
    <% end %>
  </div>
</div>