config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :athletes

  resources :competitions do
    resources :bibs, only: [:index, :create]
    resources :rounds, only: [:new, :create]
  end

  resources :bibs, only: [:edit, :update, :destroy]

  resources :rounds, only: [:show, :edit, :update, :destroy] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, only: [:show, :edit, :update, :destroy] do
    resources :attempts, only: [:new, :create, :index]
  end

  resources :attempts, only: [:edit, :update, :destroy]
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :competition
  has_many :routes
  has_many :attempts, through: :routes
  has_many :athletes, through: :attempts
  has_many :round_scores

  validates :competition, presence: true
  validates :name,
    presence: true,
    uniqueness: { scope: :competition }
  validates :number,
    presence: true,
    numericality: { only_integer: true },
    uniqueness: { scope: :competition }

  def leaderboard
    round_scores.order(tops: :desc, score: :asc)
  end

  def single_route?
    route_count == 1
  end

  def first_round?
    previous_round.nil?
  end

  def previous_round
    competition.rounds.find_by(number: (number - 1))
  end

  def top_count(athlete)
    tops = 0
    routes.each do |route|
      tops += 1 if route.top?(athlete)
    end
    tops
  end

  def round_score(athlete)
    round_scores.find_by(athlete: athlete).try(:score)
  end

  def round_tops(athlete)
    round_scores.find_by(athlete: athlete).try(:tops)
  end

  def route_count
    routes.count
  end

  def update_scores
    athletes.uniq.each do |athlete|
      total_score = routes.inject(1) do |product, route|
        product * (route.athlete_rank(athlete) || 0)
        # '|| 0' prevents errors when setting defaults
      end

      round_score = round_scores.find_or_initialize_by(athlete: athlete)
      round_score.score = (total_score.to_f**(1 / route_count.to_f)).round(2)
      round_score.tops = top_count(athlete)
      round_score.save
    end
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!, only:
    [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_owner!, only:
    [:new, :create, :edit, :update, :destroy]

  def show
    @round = Round.includes(:routes, :attempts).find(params[:id])
  end

  def new
    @competition = Competition.find(params[:competition_id])
    @round = Round.new
  end

  def create
    @competition = Competition.find(params[:competition_id])
    @round = @competition.rounds.new(round_params)

    if @round.save
      flash[:notice] = 'New round created'
      redirect_to round_path(@round)
    else
      flash[:alert] = @round.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @round = Round.find(params[:id])
  end

  def update
    @round = Round.find(params[:id])

    if @round.update(round_params)
      flash[:notice] = 'Round updated'
      redirect_to round_path(@round)
    else
      flash[:alert] = @round.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @round = Round.find(params[:id])

    if @round.destroy
      flash[:alert] = "Round deleted"
      redirect_to competition_path(@round.competition)
    else
      flash[:alert] = @round.errors.full_messages.join(". ")
      render :show
    end
  end

  protected

  def owner
    if params[:competition_id]
      Competition.find(params[:competition_id]).user
    else
      Round.find(params[:id]).competition.user
    end
  end

  def round_params
    params.require(:round).permit(
      :name, :number, :competition_id)
  end
end

app/views/rounds/edit.html.erb
<h2>
  <%= link_to @round.competition.name, competition_path(@round.competition) %>
</h2>

<h5>
  <%= @round.competition.gender %>&nbsp;
  <%= @round.competition.division %>
</h5>

<h2>Edit <%= link_to "#{@round.name} (Round #{@round.number})", round_path(@round) %></h2>

<div>
  <%= form_for @round do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :number, "Round Number" %>
    <%= f.number_field :number %>

    <p>(In a two-round competition, qualifiers would be "1" and finals would be "2")<p>

    <%= f.submit "Update Round", class: "button small" %>
  <% end %>
</div>

<p>
  <%= link_to "Delete Round", round_path(@round), method: :delete,
    data: { confirm: "This will delete round permanently" } %>
</p>

app/views/rounds/new.html.erb
<h2>
  <%= link_to @competition.name, competition_path(@competition) %>
</h2>

<h5>
  <%= @competition.gender %>&nbsp;
  <%= @competition.division %>
</h5>

<h2>Create New Round</h2>

<div>
  <%= form_for [@competition, @round] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :number, "Round Number" %>
    <%= f.number_field :number %>

    <p>(In a two-round competition, qualifiers would be "1" and finals would be "2")</p>

    <%= f.submit "Create Round", class: "button small" %>
  <% end %>
</div>

app/views/rounds/show.html.erb
<h2>
  <%= link_to @round.competition.name, competition_path(@round.competition) %> –
  <%= @round.name %> (Round <%= @round.number %>)
</h2>

<h5>
  <%= @round.competition.gender %>&nbsp;
  <%= @round.competition.division %>
</h5>

<% unless current_user == @round.competition.user %>
  <br>
  <%=
    link_to "Create your own competition to add routes and record attempts",
    new_competition_path, class: "button small"
  %>
<% end %>

<div class="row">
  <div class="small-2 columns">
    <ul class=side-nav>
      <li>
        <%=
          link_to "Overall",
          competition_path(@round.competition), class: "button small success"
        %>
      </li>
      <li><h4><strong>Routes</strong></h4></li>
      <% @round.routes.each do |route| %>
        <li>
          <%=
            link_to route.name, route_path(route),
            class: "button small success"
          %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="small-10 columns">
    <table class="center">
      <thead>
        <tr>
          <th>Standing</th>
          <th>Athlete</th>
          <% if @round.single_route? %>
            <th>
              <%= link_to @round.routes.first.name,
                route_path(@round.routes.first) %>
            </th>
            <th>Attempts*</th>
          <% else %>
            <th>Tops</th>
            <th>Round Points</th>
            <% @round.routes.each do |route| %>
              <th>
                <%= link_to route.name, route_path(route) %>
                <br>Route
              </th>
            <% end %>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @round.leaderboard.each_with_index do |score, i| %>
          <tr>
            <td><%= i + 1 %></td>
            <td><%= link_to score.athlete.name_last_first, athlete_path(score.athlete) %></td>
            <% if @round.single_route? %>
              <td><%= @round.routes.first.score_display(score.athlete) %></td>
              <td>
                <%= @round.routes.first.attempts_to_highpoint(score.athlete) %>
              </td>
            <% else %>
              <td><%= score.tops %></td>
              <td><%= score.score %></td>
              <% @round.routes.each do |route| %>
                <td>
                  <%= route.athlete_rank(score.athlete) %>
                  <% if route.top?(score.athlete) %>
                    (T)
                  <% end %>
                </td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p>
      <% if @round.single_route? %>
        * Attempts to highpoint
      <% else %>
        Ranking points are shown for routes in the current round
        <br>
        (T) indicates a "Top" (climber achieved maximum score)
      <% end %>
    </p>

    <% if current_user == @round.competition.user %>
      <%=
        link_to "Add Route", new_round_route_path(@round), class: "button small"
      %>
      &nbsp;&nbsp;
      <%=
        link_to "Edit Round", edit_round_path(@round), class: "button small"
      %>
    <% end %>
  </div>
</div>