config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :athletes

  resources :competitions do
    resources :bibs, only: [:index, :create]
    resources :rounds, only: [:new, :create]
  end

  resources :bibs, only: [:edit, :update, :destroy]

  resources :rounds, only: [:show, :edit, :update, :destroy] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, only: [:show, :edit, :update, :destroy] do
    resources :attempts, only: [:new, :create, :index]
  end

  resources :attempts, only: [:edit, :update, :destroy]
end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :round
  delegate :competition, to: :round

  has_many :attempts
  has_many :highpoints
  has_many :route_ranks
  has_many :athletes, through: :highpoints

  validates :name,
    presence: true,
    uniqueness: { scope: :round }
  validates :round, presence: true
  validates :max_score,
    presence: true,
    numericality: true

  after_save :set_default_attempts_for_route

  def set_default_attempts_for_route
    round.competition.athletes.each do |athlete|
      attempt = attempts.new(athlete: athlete, score: 0)
      attempt.save
      attempt.update_highpoint
    end

    @defaults_set = true
  end

  def leaderboard
    route_ranks.order(:rank)
  end

  def attempts_to_highpoint(athlete)
    athlete_highpoint(athlete).try(:number) || 0
  end

  def athlete_attempts(athlete)
    attempts.where(athlete: athlete).order(:created_at)
  end

  def athlete_highpoint(athlete)
    highpoints.find_by(athlete: athlete)
  end

  def athlete_rank(athlete)
    route_ranks.find_by(athlete: athlete).try(:rank)
  end

  def top?(athlete)
    athlete_highpoint(athlete).try(:top)
  end

  def score(athlete)
    athlete_highpoint(athlete).try(:score) || 0
  end

  def score_display(athlete)
    if top?(athlete)
      "TOP"
    else
      score(athlete)
    end
  end

  def update_ranks
    rerank_route
    round.update_scores
  end

  def rerank_route
    ties_hash.each do |_, ties|
      rank = determine_route_rank(ties)
      save_ranks(ties, rank)
    end
  end

  def determine_route_rank(ties)
    ties_count = ties.count
    tied_ranks_sum = 0
    ties.each { |_, rank| tied_ranks_sum += rank }
    tied_ranks_sum.to_f / ties_count.to_f
  end

  def save_ranks(ties, rank)
    ties.each do |highpoint, _|
      route_rank = route_ranks.find_or_initialize_by(
        athlete: highpoint.athlete)
      route_rank.rank = rank
      route_rank.highpoint = highpoint
      route_rank.save!
    end
  end

  def ties_hash
    ties = {}
    highpoints = sort_highpoints

    highpoints.each_with_index do |highpoint, i|
      ties[[highpoint.score, highpoint.number]] ||= {}
      ties[[highpoint.score, highpoint.number]][highpoint] = i + 1
    end
    ties
  end

  def sort_highpoints
    if @defaults_set == true
      all_highpoints = highpoints
    else
      all_highpoints = Highpoint.where(route: self) # updates eager-loaded data
    end
    all_highpoints.sort_by { |a| [-a.score, a.number] }
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :authenticate_user!, only:
    [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_owner!, only:
    [:new, :create, :edit, :update, :destroy]

  def show
    @route = Route.includes(:highpoints, :round, :attempts).find(params[:id])
    @attempt = Attempt.new
    # @athlete = @route.attempts.order(:created_at).last.athlete
  end

  def new
    @round = Round.find(params[:round_id])
    @route = Route.new
  end

  def create
    @round = Round.find(params[:round_id])
    @route = @round.routes.new(route_params)

    if @route.save
      flash[:notice] = 'New route created'
      redirect_to round_path(@round)
    else
      flash[:alert] = @route.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @route = Route.find(params[:id])
  end

  def update
    @route = Route.find(params[:id])

    if @route.update(route_params)
      flash[:notice] = 'Route updated'
      redirect_to route_path(@route)
    else
      flash[:alert] = @route.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @route = Route.find(params[:id])

    if @route.destroy
      flash[:alert] = "Route deleted"
      redirect_to round_path(@route.round)
    else
      flash[:alert] = @route.errors.full_messages.join(". ")
      render :show
    end
  end

  protected

  def owner
    if params[:round_id]
      Round.find(params[:round_id]).competition.user
    else
      Route.find(params[:id]).round.competition.user
    end
  end

  def route_params
    params.require(:route).permit(
      :name, :max_score, :round_id)
  end
end

app/views/routes/edit.html.erb
<h2>
  <%= link_to @route.round.competition.name, competition_path(@route.round.competition) %> –
  <%= link_to "#{@route.round.name} (Round #{@route.round.number})", round_path(@route.round) %>
</h2>

<h5>
  <%= @route.round.competition.gender %>&nbsp;
  <%= @route.round.competition.division %>
</h5>

<h2>Edit Route: <%= link_to @route.name, route_path(@route) %></h2>

<div>
  <%= form_for @route do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :max_score, "Maximum Score" %>
    <%= f.number_field :max_score, step: 0.01 %>

    <%= f.submit "Update Route", class: "button small" %>
  <% end %>
</div>

<p>
  <%= link_to "Delete Route", route_path(@route), method: :delete,
    data: { confirm: "This will delete route permanently" } %>
</p>

app/views/routes/new.html.erb
<h2>
  <%= link_to @round.competition.name, competition_path(@round.competition) %> –
  <%= link_to "#{@round.name} (Round #{@round.number})", round_path(@round) %>
</h2>

<h5>
  <%= @round.competition.gender %>&nbsp;
  <%= @round.competition.division %>
</h5>

<h2>Create New Route</h2>

<div>
  <%= form_for [@round, @route] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :max_score, "Maximum Score" %>
    <%= f.number_field :max_score, step: 0.01 %>

    <%= f.submit "Create Route", class: "button small" %>
  <% end %>
</div>

app/views/routes/show.html.erb
<h2>
  <%= link_to @route.round.competition.name, competition_path(@route.round.competition) %> –
  <%= link_to "#{@route.round.name} (Round #{@route.round.number})", round_path(@route.round) %>
</h2>

<div class="row">
  <div class="small-2 columns side-nav">
    <ul class="side-nav">
      <% if current_user == @route.round.competition.user %>
        <li><h4><strong>Record Attempts</strong></h4></li>
        <li>
          <div>
            <%= form_for [@route, @attempt] do |f| %>
              <%= f.label :athlete_id, "Athlete" %>
              <%= f.select :athlete_id,
                options_from_collection_for_select(
                  @route.competition.athletes.order(:last_name),
                  :id,
                  :name_last_first,
                  session[:athlete_id]
                ), include_blank: true
              %>

              <%= f.label :score %>
              <%= f.number_field :score, step: 0.01 %>

              <%= f.submit "Submit", class: "button small" %>
            <% end %>
          </div>
        </li>
      <% else %>
        <br><br><br>
      <% end %>
      <li>
        <%=
          link_to "Overall",
          competition_path(@route.round.competition),
          class: "button small success"
        %>
      </li>
      <li>
        <%=
          link_to "Round",
          round_path(@route.round), class: "button small success"
        %>
      </li>
    </ul>
  </div>
  <div class="small-10 columns">
    <h3>Route: <%= @route.name %></h3>
    <h5>Maximum score: <%= @route.max_score %></h5>
    <table class="center">
      <thead>
        <tr>
          <th>Ranking Points</th>
          <th>Athlete</th>
          <th>Route Score</th>
          <th>Attempts*</th>
        </tr>
      </thead>
      <tbody>
        <% @route.leaderboard.each do |r_rank| %>
          <tr class=<% r_rank.highpoint.css_class %>>
            <td><%= r_rank.rank %></td>
            <td><%= link_to r_rank.athlete.name_last_first, athlete_path(r_rank.athlete) %></td>
            <td><%= r_rank.highpoint.score_display %></td>
            <td><%= r_rank.number %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p>* Attempts to Highpoint</p>

    <%= link_to "All Attempts", route_attempts_path(@route), class: "button small" %>

    <% if current_user == @route.round.competition.user %>
      &nbsp;&nbsp;
      <%= link_to "Edit Route", edit_route_path(@route), class: "button small" %>
    <% end %>
  </div>
</div>