config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :athletes

  resources :competitions do
    resources :bibs, only: [:index, :create]
    resources :rounds, only: [:new, :create]
  end

  resources :bibs, only: [:edit, :update, :destroy]

  resources :rounds, only: [:show, :edit, :update, :destroy] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, only: [:show, :edit, :update, :destroy] do
    resources :attempts, only: [:new, :create, :index]
  end

  resources :attempts, only: [:edit, :update, :destroy]
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :route
  belongs_to :athlete

  delegate :round, to: :route
  delegate :competition, to: :round
  delegate :athletes, to: :competition

  validates :athlete, presence: true
  validates :route, presence: true
  validates :score,
    presence: true,
    numericality: { greater_than_or_equal_to: 0 }
  validate :validate_within_max_score, on: [:create, :update]

  after_save :update_highpoint

  def update_highpoint
    highpoint = Highpoint.find_or_initialize_by(athlete: athlete, route: route)
    if highpoint.attempt.nil? || (score > highpoint.score)
      highpoint.attempt = self
      highpoint.top = top?
      highpoint.save
    end
  end

  def validate_within_max_score
    if score
      unless score <= route.max_score
        errors.add(:score,
          "cannot be higher than route maximum score of #{route.max_score}")
      end
    end
  end

  def number
    route.athlete_attempts(athlete).rindex(self)
  end

  def highpoint?
    self == route.athlete_highpoint(athlete)
  end

  def top?
    score == route.max_score
  end

  def score_display
    if top?
      "TOP"
    else
      score
    end
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :authenticate_user!, only:
    [:create, :edit, :update, :destroy]
  before_action :authenticate_owner!, only:
    [:create, :edit, :update, :destroy]

  def index
    @route = Route.includes(:attempts, :round).find(params[:route_id])
  end

  def create
    @route = Route.find(params[:route_id])
    @attempt = @route.attempts.new(attempt_params)
    session[:athlete_id] = @attempt.athlete_id

    if @attempt.save
      flash[:notice] = 'Attempt recorded'
      redirect_to route_path(@route)
    else
      flash[:alert] = @attempt.errors.full_messages.join(". ")
      redirect_to route_path(@route)
    end
  end

  def edit
    @attempt = Attempt.find(params[:id])
  end

  def update
    @attempt = Attempt.find(params[:id])

    if @attempt.update(attempt_params)
      flash[:notice] = 'Attempt updated'
      redirect_to route_attempts_path(@attempt.route)
    else
      flash[:alert] = @attempt.errors.full_messages.join(". ")
      render :edit
    end
  end

  def destroy
    @attempt = Attempt.find(params[:id])

    if @attempt.destroy
      flash[:alert] = "Attempt deleted"
      redirect_to route_attempts_path(@attempt.route)
    else
      flash[:alert] = @attempt.errors.full_messages.join(". ")
      render :edit
    end
  end

  protected

  def owner
    if params[:route_id]
      Route.find(params[:route_id]).round.competition.user
    else
      Attempt.find(params[:id]).route.round.competition.user
    end
  end

  def attempt_params
    params.require(:attempt).permit(
      :athlete_id, :score)
  end
end

app/views/attempts/edit.html.erb
<h2>
  <%= link_to @attempt.competition.name, competitions_path(@attempt.competition) %> -
  <%= link_to @attempt.round.name, round_path(@attempt.round) %>
  (Round <%= @attempt.round.number %>)
</h2>

<h5>
  <%= @attempt.competition.gender %>&nbsp;
  <%= @attempt.competition.division %>
<br>

<h2>Route: <%= link_to @attempt.route.name, route_path(@attempt.route)%></h2>

<h2>Edit Attempt <%= @attempt.number %> for <%= @attempt.athlete.name %> <h2>

<h5>
  Recorded at: <%= @attempt.created_at %>
  <% unless @attempt.created_at == @attempt.updated_at %>
    Edited at: <%= @attempt.updated_at %>
  <% end %>
</h5>

<div>
  <%= form_for @attempt do |f| %>
    <%= f.label :athlete_id, "Athlete" %>
    <%= f.collection_select :athlete_id,
      @attempt.route.round.competition.athletes.order(:last_name),
      :id, :name_last_first, include_blank: true %>

    <%= f.label :score %>
    <%= f.number_field :score, step: 0.01 %>

    <%= f.submit "Edit Attempt", class: "button small" %>
  <% end %>
</div>

<p>
  <%= link_to "Delete Attempt", attempt_path(@attempt), method: :delete,
    data: { confirm: "This will delete attempt permanently" } %>
</p>

<%= link_to "Back to All Attempts", route_attempts_path(@attempt.route) %>

app/views/attempts/index.html.erb
<h2>
  <%= @route.competition.name %> - <%= link_to @route.round.name, round_path(@route.round) %>
  (Round <%= @route.round.number %>)
</h2>

<h5>
  <%= @route.competition.gender %>&nbsp;
  <%= @route.competition.division %>
<br>

<h2>Route: <%= link_to @route.name, route_path(@route)%></h2>

<h4>All Attempts</h4>
<h5>Maximum score: <%= @route.max_score %></h5>

<table class="center">
  <thead>
    <tr>
      <th>Athlete</th>
      <th>Score</th>
      <th>Attempt #</th>
      <% if current_user == @route.competition.user %>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @route.attempts.each do |attempt| %>
      <% unless attempt.number == 0 %>
        <tr class=<% attempt.class %>>
          <td><%= attempt.athlete.name %></td>
          <td><%= attempt.score %></td>
          <td><%= attempt.number %></td>

          <% if current_user == @route.round.competition.user %>
            <td><%= link_to "Edit Attempt", edit_attempt_path(attempt) %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>